name: Generate Assets

on:
  push:
    branches:
      - main

jobs:
  auto-update:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'release:')
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: pip cache
      id: pip-cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: node cache
      id: node-cache
      uses: actions/cache@v2
      with:
        path: |
          .yarn/cache
          **/tsconfig.tsbuildinfo
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: pip install -r ./requirements.txt
    - run: yarn install --immutable
    - name: Build Dependency
      run: |
        yarn workspaces foreach -pt run build
    - name: Generate webfonts
      run: |
        yarn workspaces foreach -pt run subset
    - name: Update example assets
      run: |
        cp -f ./packages/pretendard/dist/public/static/Pretendard-*.otf ./examples/flutter_pretendard/fonts
        cp -f ./packages/pretendard/dist/public/static/Pretendard-*.otf ./examples/react_native_pretendard/assets/fonts
    - name: Commit Build File
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
        file_pattern: packages/*/dist/web/** examples/**
        commit_message: 'fix: Auto-generate assets'
