name: Release CI

on:
  push:
    tags:
      'v*' # push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  upload:
    name: Upload Assets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-yarn
    - name: Set env
      run: |
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        echo "RELEASE_NAME=${RELEASE_VERSION:1}" >> $GITHUB_ENV
    - name: Publish to NPM
      run: |
        # Publish
        yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
        yarn workspaces foreach run publish
    - name: Zip
      run: |
        cd packages

        # Remove Dynamic Subset Files
        find -wholename "**/web/*/*dynamic-subset*" -delete
        find -wholename "**/web/*/Pretendard*.css"  -delete

        # Zip
        (cd pretendard/dist && zip -rv - .) > Pretendard-${{ env.RELEASE_NAME }}.zip
        (cd pretendard-jp/dist && zip -rv - .) > PretendardJP-${{ env.RELEASE_NAME }}.zip
        (cd pretendard-std/dist && zip -rv - .) > PretendardStd-${{ env.RELEASE_NAME }}.zip
        (cd pretendard-gov/dist && zip -rv - .) > PretendardGOV-${{ env.RELEASE_NAME }}.zip
    - uses: softprops/action-gh-release@v1 # actions/create-release, actions/upload-release-asset is deprecated
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          packages/Pretendard-${{ env.RELEASE_NAME }}.zip
          packages/PretendardJP-${{ env.RELEASE_NAME }}.zip
          packages/PretendardStd-${{ env.RELEASE_NAME }}.zip
          packages/PretendardGOV-${{ env.RELEASE_NAME }}.zip
  jsdelivrpurge:
    name: Purge jsDelivr cache
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    needs: upload
    steps:
    - name: Set up NodeJS LTS
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    - name: Run jsDelivr-Purge
      uses: List-KR/jsdelivr-purge@5.2.0

