name: Release CI

on:
  push:
    tags:
      'v*' # push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        echo "RELEASE_NAME=${RELEASE_VERSION:1}" >> $GITHUB_ENV
    - name: Zip
      run: |
        cd dist
        zip -rv Pretendard-${{ env.RELEASE_NAME }}.zip *
    - uses: softprops/action-gh-release@v1 # actions/create-release, actions/upload-release-asset is deprecated
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/Pretendard-${{ env.RELEASE_NAME }}.zip
